### ISSUE TITLE
long integer no longer exists in python3

### ISSUE THREAD

**Issue by edhinard** [ANSSI-FR/pycrate#1]
can't compile module with python3 because of long int literals, like for example 'ub=4294967295L' in SNMP.py line 148
int and long int are unified since python3, thus 'L' suffix does not exists. The good news is that python2.7 automatically use long integer when needed. You could remove all terminating 'L' on integer literals to make your code python2/3 compatible

**Comment by mitshell** [comment]
Thanks for reporting, commit 60cb721 has updated the python code generator and python ASN.1 specifications. Now, those should load correctly both with Py2 and Py3.
