### ISSUE TITLE
class ASN1Obj(Element) attributes

### ISSUE THREAD

**Issue by p1-scg** [ANSSI-FR/pycrate#17]
Hello,

I have a question about implementation of attributes in class ASN1Obj:
 ``` 
    _name    = ''
    _mode    = MODE_TYPE
    _tag     = None
    _typeref = None
    _tr      = None
    _param   = False
    _parent  = None
    _opt     = False
    _def     = None
    _uniq    = False
    _group   = None
    _cont    = None
    _root    = None
    _ext     = None
    _val     = None
```
and I didn't catch up why there is in the Class, so it is a static value.
Especially, when you use decode an object with method from_ber(), and then you
decode another object with the same method (but empty value). The _val
variable will keep the value of the first object.
What is the reason of the class-level implementation vs the obj-level implementation?

Thanks,

**Comment by mitshell** [comment]
Class attributes provide default values for all attributes.
Instance attributes provide, when defined, specific values that masquerade those from the class.
This saves some memory.

**Comment by p1-scg** [comment]
Thank you for the explanation, I close the issue.
