### ISSUE TITLE
Empty sequence are wrongly serialized in UPER

### ISSUE THREAD

**Issue by maximeB** [ANSSI-FR/pycrate#23]
### Pycrate versions
* pycrate-0.2 
* pycrate-0.3

### Steps to reproduce
The following ASN.1 definition reproduce the bug:
```ASN.1
BEGIN
OneByteMessage ::= SEQUENCE {
      fourBits   INTEGER (0..15),
      oneBit     SEQUENCE {...},
      threeBits BIT STRING (SIZE(3))
  }
END
```
Using pycrate with the following test set:
```python
test = {'fourBits': 15,
    'oneBit': {},
    'threeBits': (7,3)
}
```
Results in `0xFE` where it should have been `0xF7`.  
The first four bits are indeed set to `0xF` in both cases, but then with pycrate the oneBit field is elided and we find the threeBits set to `0b111` which makes the `0xE`.

Expected result can be checked at [asn1-playground](http://asn1-playground.oss.com/) by using the following data to encode: 
```ASN.1
data OneByteMessage ::= 
{  
    fourBits   15,
    oneBit     {},
    threeBits '111'B
}

```

**Comment by mitshell** [comment]
Thanks for reporting,
this will fix the issue: https://github.com/ANSSI-FR/pycrate/commit/209cefe4c1929b7a059c718f529be4a6c22059b1
