### ISSUE TITLE
are you have any plan to support 36.321, 36.322, 36.323 specification decoding support?

### ISSUE THREAD

**Issue by jothikumarmani** [ANSSI-FR/pycrate#24]
are you have any plan to support 36.321, 36.322, 36.323 specification decoding support?
I can see that NAS and RRC are present, I am not seeing any option to raise it as a question so submitting as an issue.

thankyou.

**Comment by mitshell** [comment]
No plan for such support on my side.
The main reason is that I have no hardware or software with a nice and clean API to interface at such MAC / RLC layer easily.
