### ISSUE TITLE
Problem with APER encoding empty container of ProtocolIEs in S1AP

### ISSUE THREAD

**Issue by kalin1993** [ANSSI-FR/pycrate#3]
Hi, I've tried to use your library but I''ve encountered problem with encoding following S1AP message : `('successfulOutcome', {'procedureCode': 14, 'value': ('ResetAcknowledge', {'protocolIEs': []}), 'criticality': 'reject'})`
to_aper function returns following bytes 20 0E 00 01 00 but should return 20 0E 00 03 00 00 00

**Comment by mitshell** [comment]
Thanks for reporting the bug.
Commit https://github.com/ANSSI-FR/pycrate/commit/ef31fc0fa58ee587d5ce6f68fdae0c2b7ad4f194 should fix this.
