### ISSUE TITLE
ServerAuC make_4g_vector() function

### ISSUE THREAD

**Issue by GinesGarcia** [ANSSI-FR/pycrate#9]
Hi,
I'm trying to generate the authentication vector using this function, but I got the following error:
  - global name "xor_buf" is not defined
where can I find the function implementation?

Thanks in advance!

**Comment by mitshell** [comment]
Hi,
as stated in the readme (https://github.com/ANSSI-FR/pycrate#dependencies), you need CryptoMobile: https://github.com/mitshell/CryptoMobile
Benoit

**Comment by GinesGarcia** [comment]
Thanks for your reply but I have already installed CryptoMobile. The problem was the function name itself.

thanks

**Comment by mitshell** [comment]
It's there:

**Comment by mitshell** [comment]
https://github.com/mitshell/CryptoMobile/blob/master/CryptoMobile/utils.py
